apiVersion: v1
kind: Service
metadata:
    name: ngnix_service
    namespace: argocd
spec:
    selector:
        service: ngnix_pod
    ports:
      - port: 80
        targetPort: 80
    type: NodePort    
          
