apiVersion: apps/v1
kind: Deployment
metadata:
    name: ngnix
    namespace: argocd
    labels:
       app: ngnix
spec:
   replicas: 3
   selector:
       matchLabels:
           app: ngnix
   template:
       metadata:
           labels:
               app: ngnix
               service: ngnix-pod
       spec:
           containers:
              - name: ngnix-app
                image: ngnix
                ports:
                  - containerPort: 80
                
          
       
