apiVersion: v1
kind: Service
metadata:
    name: ngnix-service
    namespace: argocd
spec:
    selector:
        service: ngnix-pod
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
    type: LoadBalancer   
          
