apiVersion: apps/v1
kind: Deployment
metadata:
    name: ngnix
    namespace: argocd
    labels:
       app: ngnix
spec:
   replicas: 3
   selector:
       matchLabels:
           app: ngnix
   template:
       metadata:
           labels:
               app: ngnix
       spec:
           containers:
              - name: ngnix_app
                image: ngnix:latest
                ports:
                  - "80:80"
                
          
       
